# Base configs
baseurl: "/photography-portfolio"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Bingqi Shang"
subtitle: "Astrophotography collection"
author: "Bingqi Shang"
header:
 title: "Photography"
 subtitle: "by Bingqi Shang"
footer:
 name: "Hey there, my name is Bingqi Shang"
 bio: "I am an amateur astrophotographer specializing in capturing the wonders of the night sky. The images on this website represent collaborative work between myself, Yiming Mao, and Yunfan Liu, as astrophotography is truly a team effort."
 github: "https://github.com/olivershang"
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  twitter: ""
  instagram: ""
  dribbble: ""
  linkedin: ""
  github: "https://www.github.com/olivershang"
